language: elixir
matrix:
  include:
    - otp_release: 19.0
      elixir: 1.4.0
      script: mix test
dist: trusty
sudo: false
services:
  - mongodb
before_script:
  - mix deps.get
  - sleep 10
script:
  - mix test
  
