language: elixir
matrix:
  include:
    - otp_release: 19.0
      elixir: 1.4.0
dist: trusty
sudo: false
services:
  - postgresql  
before_script:  
  - psql -c "CREATE USER estacionapp WITH PASSWORD 'estacionapp' SUPERUSER;" -U postgres
  - psql -U postgres -c "CREATE EXTENSION postgis"
  - mix deps.get
script:
  - mix test
