language: elixir
matrix:
  include:
    - otp_release: 19.0
      elixir: 1.4.0
dist: trusty
sudo: false
addons:
  postgresql: "9.5"
  apt:
    packages:
      - postgresql-9.5-postgis-2.3
before_script:  
  - psql -c "CREATE USER estacionapp WITH PASSWORD 'estacionapp' SUPERUSER;" -U postgres
  - psql -U postgres -c "CREATE EXTENSION postgis"
  - mix deps.get
script:
  - mix test
